apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jlpx50kng-python 
  janus-idp.io/tekton: jlpx50kng-python
  backstage.io/kubernetes-id: jlpx50kng-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlpx50kng-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml